# Kind cluster configuration for Cilium CNI testing
# Disables default CNI to allow Cilium installation
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubecompass-cilium
networking:
  # Disable default kindnet CNI
  disableDefaultCNI: true
  # Cilium needs kube-proxy disabled for full feature set
  kubeProxyMode: "none"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "enable-admission-plugins": "NodeRestriction"
